#!/usr/bin/env node

var del = require('./lib/del'),
    add = require('./lib/add');

var argv = require('yargs')
    .usage('Usage: [user] [mapid or datasetid] [data?]')
    .demand(2)
    .argv;

del(argv._[0], argv._[1], function(e) {
    if (e) throw e;
    add(argv._[0], argv._[1], argv._[2], function(err, res, data) {
        if (err) throw err;
        console.error('added/uploaded %s features', JSON.parse(data).features.length);
    });
});
