#!/usr/bin/env node

require('update-notifier')({ pkg: require('./package.json') }).notify();
var MapboxDatasets = require('mapbox/lib/services/datasets');

var argv = require('yargs')
    .usage('Usage: mapbox-data-create [name?] [description?] [--user userid]')
    .demand(0, 2)
    .argv;

var opts = argv.user ? { account: argv.user } : {};
var client = new MapboxDatasets(process.env.MapboxAccessToken, opts);

client.createDataset({ name: argv._[0], description: argv._[1] }, function(e, dataset) {
    if (e && e.statusCode === 404) {
        console.error('Error: user not found (make sure your MapboxAccessToken environment variable has the datasets:write scope)');
        throw e;
    }
    if (e) throw e;
    console.log(JSON.stringify(dataset));
});
