#!/usr/bin/env node

require('update-notifier')({ pkg: require('./package.json') }).notify();
var MapboxDatasets = require('mapbox/lib/services/datasets');
var argv = require('yargs')
    .usage('Usage: <mapid or datasetid> [featureid?] [--user userid]')
    .demand(1, 2)
    .argv;

var opts = argv.user ? { account: argv.user } : {};
var client = new MapboxDatasets(process.env.MapboxAccessToken, opts);

if (argv._[1]) {
    client.deleteFeature(argv._[1], argv._[0], function(err, res) {
        if (err && err.statusCode === 404) {
            console.error('Error: user not found (are you using a token with datasets:write scope?)');
            throw err;
        }
        if (err) throw err;
        console.log(JSON.stringify(res));
    });
} else {
    client.deleteDataset(argv._[0], function(err, res) {
        if (err && err.statusCode === 404) {
            console.error('Error: dataset not found (are you using a token with datasets:write scope?)');
            throw err;
        }
        console.error(err);
        if (err) throw err;
        console.log(JSON.stringify(res));
    });
}
