#!/usr/bin/env node

require('update-notifier')({ pkg: require('./package.json') }).notify();
var MapboxDatasets = require('mapbox/lib/services/datasets');
var getInput = require('./lib/util/get_input');
var argv = require('yargs')
    .usage('Usage: mapbox-data-add <mapid or datasetid> <filename> [--user userid]')
    .demand(2)
    .argv;

var opts = argv.user ? { account: argv.user } : {};
var client = new MapboxDatasets(process.env.MapboxAccessToken, opts);

getInput(argv._[1], function(err, features) {
    (function makeRequest(leftToDo) {
        var body = {
            put: leftToDo.splice(0, 100)
        };

        client.bulkFeatureUpdate(body, argv._[0], function(err, data) {
            if (err) throw err;

            data.put.forEach(function(feature) {
                console.log(JSON.stringify(feature));
            });

            if (leftToDo.length) return makeRequest(leftToDo); 
        });
    })(features);
});
