#!/usr/bin/env node

var get = require('./lib/get');
var argv = require('yargs')
    .usage('Usage: [user] [mapid or datasetid]')
    .demand(2)
    .argv;

get(argv._[0], argv._[1], function(err, res) {
    if (err) throw err;
    console.log(res);
});
